server:
  port: 8080
  servlet:
    context-path: /
google:
  translate:
    api:
      url: https://translation.googleapis.com/v3
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
logging:
  level:
    com.translate.server: INFO
